### ISSUE TITLE
component fails to load

### ISSUE THREAD

**Issue by scottleblanc** [pimlie/vue-bootstrap-slider#1]
I get the following error when trying to load component in Vue 2:

Failed to mount component: template or render function not defined.

import VueBootstrapSlider from 'vue-bootstrap-slider';

'inputslider': VueBootstrapSlider

`<inputslider :value="this.filterCalories"/>`

**Comment by pimlie** [comment]
Thanks for reporting, it seems the export for the vue component itself is missing. Now it only exports the VuePlugin you can use directly in the browser. Will push a new version later today which will also add some tests and clearer readme.

**Comment by pimlie** [comment]
Version 1.1 has been pushed, please note that the default export of this package is a VuePlugin. See the updated README

**Comment by ribrewguy** [comment]
I'm seeing this as still unresolved in 1.1.1.

In my component I have:
```
import Vue from 'vue';
import bFormSlider from 'vue-bootstrap-slider';

Vue.use(bFormSlider);

export default {
  bFormSlider,
};
```

In the template I have: `<b-form-slider :value="myValue" />`

It will still not load: `Failed to mount component: template or render function not defined.`

**Comment by fullstackfool** [comment]
@redijedi try removing:

`export default {
  bFormSlider,
};`

**Comment by pimlie** [comment]
@redijedi Sorry, it seems I missed your comment. 
@fullstackfool Thanks for the help, that should indeed do the trick :)

You can also have a look otherwise at the implementation as a nuxt plugin: https://github.com/pimlie/nuxt-bootstrap-slider/blob/master/plugin.js
