### ISSUE TITLE
Issue from bump to v1.3.2 to v1.3.3

### ISSUE THREAD

**Issue by u01jmg3** [pimlie/vue-bootstrap-slider#10]
Hello, thanks for providing this excellent repo.

- https://github.com/pimlie/vue-bootstrap-slider/compare/v1.3.2...v1.3.3

Has something drastic changed between [`v1.3.2`](https://github.com/pimlie/vue-bootstrap-slider/releases/tag/v1.3.2) and [`v1.3.3`](https://github.com/pimlie/vue-bootstrap-slider/releases/tag/v1.3.3)? I am finding that a previously working slider when changed no longer updates `value` on the Vue instance. Both are using the [`v10.4.0`](https://github.com/seiyria/bootstrap-slider/releases/tag/v10.4.0) version of [`seiyria/bootstrap-slider`](https://github.com/seiyria/bootstrap-slider). Updating to the latest (`v2.0.1`) and the issue remains. Thanks

**Comment by pimlie** [comment]
In v1.3.3 the bFormSlider export was removed, see also #9. I have now deprecated v1.3.3

Do you use the bFormSlider export? If so, please check the updated readme on how to use the export

**Comment by u01jmg3** [comment]
Thanks - I hadn't assumed a breaking change between those minor version increments. Perhaps in the readme it could be made clearer that since version `v1.3.3` (`v2.0.0`) it is now a requirement to manually import `bFormSlider` should it be needed. Referencing the version at which this requirement came into play would be aimed at those who had existing, working code.

> Do you use the bFormSlider export?

I do. For info I had to add `npm add @babel/runtime`. I can see that `value` is now updated on the Vue instance. However the slider is jumping back to its original value everytime any other data is updated on the Vue instance. This didn't happen in `v1.3.2`. Is there something else I am missing that is now required?

**Comment by pimlie** [comment]
Yeah, releasing v1.3.3 was a mistake thats why I quickly released v2.0.0 (and I should've deprecated 1.3.3 sooner so it couldnt be installed, so sorry about that).

Could you create a jsfiddle-like reproduction for the issue you mentioned?

**Comment by u01jmg3** [comment]
> Could you create a jsfiddle-like reproduction for the issue you mentioned?

Baked into an application that pushes to an API endpoint using Axios. Will attempt to create a CodePen but might take me some time. For now downgrading to `v1.3.2`.

**Comment by pimlie** [comment]
Could the value issue be related to #11? It appears bootstrap-slider v10.3.4 introduced a value change issue. Could you please also check if your issue still exists with v10.3.3 ?

**Comment by u01jmg3** [comment]
Nope, the issue I am facing remains in `v10.3.3`. I also checked `v10.4.1` with your PR fix and again the issue remains. I still need to make a CodePen but here is a quick animated Gif. The Slider changes back to its starting value every time any other data on the Vue instance is modified. This didn't happen before `v1.3.2` (e.g. `v1.3.2` is the last working version for me).

![demo](https://user-images.githubusercontent.com/1266205/50163799-209f9980-02d9-11e9-82a9-a51e686bcdc9.gif)

**Comment by pimlie** [comment]
It seems that bootstrap-slider doesnt copy the state on a slider refresh and it regards the value as a state prop. Therefore it resets to the input.defaultValue. 

It feels a bit hacky-wacky, but I fixed it by checking the value after the slider refresh and re-set the value if needed. Please check v2.1.0 for these changes

**Comment by u01jmg3** [comment]
[`acdcf4e`](https://github.com/pimlie/vue-bootstrap-slider/commit/acdcf4e0444a72647235e83f53b993a4768bd7a9#diff-df0a36d86ad21b6fc2541ba32161f5ffR42) did the trick - any idea how it was introduced as an issue after `v1.3.2`?

Thank you for fixing

**Comment by pimlie** [comment]
No, still looking into that. Could you maybe share some code how you use the slider component? It could help me understand the issue.

Its strange because I can reproduce the issue with the (jest) tests, but up to now I cant reproduce it with the example.html The only thing I have noticed is that with example.html the value attribute of the input element is updated when you set the components value, but when I log the outerHTML of the input element in the test it remains at `value="50"` because of which the value is reset after a refresh (thats because in bootstrap-slider the `value` is regarded as state and is not copied to the new slider element like the options are when you refresh). But not sure yet why the value attribute is not being updated.

**Comment by u01jmg3** [comment]
It's a Laravel app. Tried to slim it down as much as possible. Hope it helps.

- `package.json`

```json
"dependencies": {
	"axios": "^0.18",
	"uiv": "^0.23.1",
    "vue": "^2.5.21",
    "vue-bootstrap-slider": "^2.0.2"
}
```

- `app.js`

```js
window.axios     = require('axios');
window.Vue       = require('vue');
window.uiv       = require('uiv');
window.VueSlider = require('vue-bootstrap-slider');
```

- `form.blade.php`

```html
<b-form-slider :formatter="sliderFormatter" v-model="alerts[index].alert_time" class="margin-bottom-35 form-control pointer station-alert-time" required="true" tooltip="always" tooltip-position="bottom" :step="0.5" :min="0.5" :max="{{ $exam->exam_station_duration }}" :ticks-labels='["{{ $exam->exam_station_duration }} minute Station"]' />
```

- `form-js.blade.php`

```js
Vue.component('Alert', uiv.Alert);
Vue.component('BFormSlider', VueSlider);

var template_alert = { id: '', alert_message: '', alert_time: {{ $default_alert_time }}, };
var new_alert      = new Vue({
    el: '.form-alerts',
    data: {
        alerts: [],
        errors: [],
        submitted: false,
        showGlobalSuccess: false,
        showGlobalError: false,
        form: $('.form-alerts').find('form'),
        isInLockdown: Boolean({{ $is_in_lockdown }}),
        disableButtons: false,
        sliderFormatter: function (value) {
            if (value === 1) {
                return value + ' ' + '{{ $suffix }}';
            }

            return value + ' ' + '{{ str_plural($suffix) }}';
        },
    },
    mounted: function () {
        var self = this;

        axios.get('{{ route($attachment_get_url, [$exam_id, $station_id, Attachment::ALERT]) }}', { params: { location: '{{ StringHelper::encryptString(Route::currentRouteName()) }}' } })
            .then(function (response) {
                if (response.status == 200) {
                    var data = response.data;
                    if (data instanceof Object && data.length) {
                        self.alerts = data;
                    } else {
                        self.alerts = [Vue.util.extend({}, template_alert)];
                    }
                }
        });
    },
    methods: {
        addNewAlert: function () {
            if (this.isInLockdown) {
                this.disableButtons = true;

                return false;
            }

            if (this.alerts.length < 5) {
                this.alerts.push(Vue.util.extend({}, template_alert));
            }

            this.showGlobalSuccess = false;
        },
        removeAlert: function (index) {
            if (this.isInLockdown) {
                this.disableButtons();

                return false;
            }

            if (this.errors['alerts.' + index + '.alert_time']) {
                delete this.errors['alerts.' + index + '.alert_time'];
            }

            if (this.errors['alerts.' + index + '.alert_message']) {
                delete this.errors['alerts.' + index + '.alert_message'];
            }

            this.alerts.splice(index, 1);

            this.showGlobalSuccess = false;
        },
        isDisabled: function (key) {
            if (this.isInLockdown) {
                return true;
            }

            if (this.alerts.length) {
                return (this.alerts.filter(function (alert) { return !!alert[key]; }).length > 0) ? false : true;
            }
        },
        getSuccessMessage: function () {
            var attached = this.alerts.length;

            if (attached === 1) {
                return '{!! trans("messages.alert_created_single") !!}';
            }

            return v.sprintf('{!! trans("messages.alert_created_multiple") !!}', attached);
        },
        getErrorMessage: function (index, errors) {
            var output = [];

            for (var error; error = errors.pop();) {
                if (this.errors['alerts.' + index + '.' + error]) {
                    var icon = '';
                    if (!this.showGlobalError) {
                        icon = '<span class="icon icon-exclamation-circle" aria-hidden="true"></span> ';
                    }
                    output.push(icon + this.errors['alerts.' + index + '.' + error]);
                }
            }

            return (output.length > 0) ? output.join('<br>') : '';
        },
        onSubmit: function (e) {
            var self = this;

            self.disableButtons = true;

            if (self.isInLockdown) {
                return false;
            }

            axios.post('{{ route($attachment_post_url, [$exam_id, $station_id, Attachment::ALERT]) }}', { alerts: self.alerts }, { params: { location: '{{ StringHelper::encryptString(Route::currentRouteName()) }}' } })
                .then(function (response) {
                    var output = response.data.output;

                    for (var key in output) {
                        self.alerts[key].id            = String(output[key].id);
                        self.alerts[key].alert_message = String(output[key].alert_message);
                        self.alerts[key].alert_time    = parseFloat(output[key].alert_time);
                    }

                    self.errors            = []; // Clear Errors
                    self.showGlobalSuccess = true;
                    self.showGlobalError   = false;
                    self.disableButtons    = false;

                    $('input[readonly], textarea[readonly]').each(function(){
                        $(this).prop('readonly', false);
                    });
                })
                .catch(function (error) {
                    var response = error.response;

                    self.errors = response.data.errors;
                    if (self.errors.type === 1) {
                        self.showGlobalError = true;
                    } else {
                        self.showGlobalError = false;
                    }
                    self.showGlobalSuccess = false;
                    self.disableButtons    = false;

                    $('input[readonly], textarea[readonly]').each(function(){
                        $(this).prop('readonly', false);
                    });
                });

            self.submitted = true;
        },
        onReset: function (e) {
            var self = this;

            self.disableButtons = true;

            if (self.isInLockdown) {
                return false;
            }

            axios.get('{{ route($attachment_delete_url, [$exam_id, $station_id, Attachment::ALERT]) }}', { params: { location: '{{ StringHelper::encryptString(Route::currentRouteName()) }}' } })
                .then(function (response) {
                    self.alerts         = [Vue.util.extend({}, template_alert)];
                    self.errors         = []; // Clear Errors
                    self.disableButtons = false;
                    $('.confirmation-to-remove-all-saved-alerts').modal('hide');
                })
                .catch(function (error) {
                    var response = error.response;

                    self.errors = response.data.errors;
                    if (self.errors.type === 1) {
                        self.showGlobalError = true;
                    } else {
                        self.showGlobalError = false;
                    }
                    self.disableButtons = false;
                    $('.confirmation-to-remove-all-saved-alerts').modal('hide');
                });
        },
    },
});
```

**Comment by pimlie** [comment]
He thanks for the information. I am still not sure why it didnt work in v1.3.3, because if I look back it shouldnt have worked in v1.3.2 either :) See https://github.com/seiyria/bootstrap-slider/issues/901

Thanks to @jespirit over at bootstrap-slider we can no keep using the current value after a refresh!
