### ISSUE TITLE
Range Slider values updating with v-model

### ISSUE THREAD

**Issue by maximedefrancq** [pimlie/vue-bootstrap-slider#13]
Hello again,

Thank you for your fix, it works well but I now encounter another bug : 
[demo gif](http://g.recordit.co/VV96Q516bS.gif)

The value of the other slider changes randomly when I overlap it or when I move the other one. This occurs only if I use v-model. I am also using vuex to get and store the values.

Thanks for your help !

**Comment by pimlie** [comment]
What do you mean with it only occurs when using v-model? Did you try it in vanilla bootstrap-slider? If not, could you take a look if you can reproduce it in seiyria's bootstrap-slider?

**Comment by maximedefrancq** [comment]
Hi,

It works well using v-model on a local variable from data(), but when using a variable from a vuex store it triggers the bug, both sliders change randomly.

I'm using `v-model="priceRange"` with this code in computed :

```priceRange: {
                get() {
                    return [parseInt(this.$store.state.filters.minPrice), parseInt(this.$store.state.filters.maxPrice)];
                },
                set(value) {
                    this.$store.commit('updateFilter', {filter: 'minPrice', value: value[0]});
                    this.$store.commit('updateFilter', {filter: 'maxPrice', value: value[1]});
                }
            },```

**Comment by maximedefrancq** [comment]
I was able to make it work by using a local variable with v-model and using watch on this variable to update my Vuex store.

Thanks again

**Comment by pimlie** [comment]
Let me know if you experience another issue
