### ISSUE TITLE
Add note that jQuery is required

### ISSUE THREAD

**Issue by kathgironpe** [pimlie/vue-bootstrap-slider#14]
Thanks for this. I think it works but for those who do not have `jQuery`.

```
Uncaught Error: Cannot find module "jquery"
```

It would be good to add the note on the dependency.

**Comment by pimlie** [comment]
Hi, thanks for your remarks. jQuery is a dependency but its not used. Unfortunately this is a quirk of the bootstrap-slider package but you can work around it. If you use Nuxt, please read this note how to stub the jquery dependency with an empty file: https://github.com/pimlie/vue-bootstrap-slider#exclude-jquery-dependency. 

But please note that that jQuery note should be an indicator that this package is only a wrapper and not really a Vue component / control. If you prefer a Vue-only project you might want to consider to use a real Vue slider component as eg https://github.com/NightCatSama/vue-slider-component
