### ISSUE TITLE
Typescript support ?

### ISSUE THREAD

**Issue by dyesdyes** [pimlie/vue-bootstrap-slider#15]
Hey,

When i try to import it, using typescript, it tells me that I need to import the @types but there doesn't seem to be any.

What should I do?

**Comment by pimlie** [comment]
At the moment this component does not support typescript. I am open to any pr which adds that, but as this component is just a wrapper around bootstrap-slider I think it would be better if they add types first which we could then extend

**Comment by dyesdyes** [comment]
It already exists and it's in this package: @types/bootstrap-slider
Thanks for your quick reply :)

**Comment by pimlie** [comment]
Ah great, nice find! I did search the bootstrap-slider repo but couldnt find any mentions about typings...
