### ISSUE TITLE
How can I get the rangeHightlights working?

### ISSUE THREAD

**Issue by carlosgj94** [pimlie/vue-bootstrap-slider#5]
Thanks for your **awesome** work 😄 
I am having issues get the rangeHightlights to work. They don't show at all...
This is the code I am using:
```
<b-form-slider 
  :v-model='hourValue'
  :value='0'
  :min='0'
  :max='119'
  :step='1'
  :rangeHighlights='[{ "start": 0, "end": 24, "class": "primary-slider" },
                        { "start": 24, "end": 47, "class": "secondary-slider" },
                        { "start": 47, "end": 71, "class": "primary-slider"},
                        { "start": 71, "end": 95, "class": "secondary-slider"},
                        { "start": 95, "end": 119, "class": "primary-slider"}]'
```

Any idea of how making it work?
Thanks a lot!

**Comment by pimlie** [comment]
Hi, thanks for the clear bug example. The `rangeHighlights` prop in bootstrap-slider does not adhere to the same case-style as the other props and therefor failed. I added an exception for this and now it should work, see the test case :)
