### ISSUE TITLE
Bootstrap Slider - Defining a Formatter

### ISSUE THREAD

**Issue by u01jmg3** [pimlie/vue-bootstrap-slider#6]
Hello,

Just wanted to know how I would go about defining a formatter for Bootstrap Slider as this cannot be passed as a `data-` attribute.

> _formatter callback. Return the value wanted to be displayed in the tooltip, useful for string values._

Many thanks!

**Comment by pimlie** [comment]
Although in vanilla html/js you can't pass a function as `data-` attribute, with Vue.js it is possible to pass a Function as property to a component:

```js
<template>
  <vue-bootstrap-slider :formatter="myFormatter"></vue-bootstrap-slider>
</template>

<script>
export default {
  data() {
    return {
      myFormatter: value => {
        return 'Value: ' + value
      }
  }
}
</script>
