### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by elbojoloco** [pimlie/vue-bootstrap-slider#8]
**Error message in console when sliding any vue-bootstrap-slider**
Unable to preventDefault inside passive event listener invocation.

**Steps to recreate**
just slide any slider on a mobile device (no error on desktop)

It still functions correctly, but there is still this error message, i have not set any passive listeners in my app manually, so it cant be that.

**Visual**
![slideerror](https://user-images.githubusercontent.com/7912315/48948926-85fca680-ef36-11e8-881f-373d8c3f784f.gif)

**Comment by pimlie** [comment]
@elbojoloco Thanks for the report, unfortunately this message is generated in upstream so outside of our control. Please check here for more information: https://github.com/seiyria/bootstrap-slider/issues/842
